apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  namespace: kurad
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    #cert-manager.io/issuer: "letsencrypt-staging"

spec:
  ingressClassName: nginx
#  tls:
#  - hosts:
#    - example.example.com
#    secretName: quickstart-example-tls
  rules:
  - host: kurad.devops-labs.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 80