apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver
  namespace: argocd
spec:
  destination:
    namespace: test-apps
    server: https://kubernetes.default.svc
  source:
    path: ./argocd/apps/echoserver
    repoURL: https://github.com/mustafa-abdelnasser/DevOps_EKS_Lab
    targetRevision: EKS-AWS-ALB-Controller
  project: eks-devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true